Improve error message for missing check_specs (#20197)
Previously if you forgot to put `check_specs` on your asset, you'd get

```
KeyError: NodeHandle(name='my_asset', parent=None)

Stack Trace:
  File "/Users/johann/dagster/python_modules/dagster/dagster/_core/execution/plan/execute_plan.py", line 286, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/johann/dagster/python_modules/dagster/dagster/_core/execution/plan/execute_step.py", line 529, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/Users/johann/dagster/python_modules/dagster/dagster/_core/execution/plan/execute_step.py", line 202, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/Users/johann/dagster/python_modules/dagster/dagster/_core/execution/plan/execute_step.py", line 101, in _process_asset_results_to_events
    yield from _process_user_event(step_context, user_event)
  File "/Users/johann/dagster/python_modules/dagster/dagster/_core/execution/plan/execute_step.py", line 131, in _process_user_event
    asset_check_evaluation = user_event.to_asset_check_evaluation(step_context)
```

when you returned an AssetCheckResult.