helm: NOTES.txt correction (#17435)
This PR Corrects component name for dagster-webserver, and turn it from
the hardcoded into dynamic one.

## Summary & Motivation

I wasn't able to quick start using hlm chart, because NOTES have me
wrong instructions.
```shell
# upgrade-installing dagster into dagster namespace with dagster/dagster with default settings.
helm --namespace=dagster upgrade dagster dagster/dagster --install
> ...
> export DAGSTER_WEBSERVER_POD_NAME=$(kubectl get pods --namespace dagster -l "app.kubernetes.io/name=dagster,app.kubernetes.io/instance=dagster,component=webserver" -o jsonpath="{.items[0].metadata.name}")
> ...
```

which results in 
```shell
> kubectl get pods --namespace dagster -l "app.kubernetes.io/name=dagster,app.kubernetes.io/instance=dagster,component=webserver" -o jsonpath="{.items[0].metadata.name}"
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
                {.items[0].metadata.name}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":""}}
```

## How I Tested These Changes
```shell
helm --namespace=dagster upgrade dagster ./dagster-repo/helm/ --install 
> ...
> export DAGSTER_WEBSERVER_POD_NAME=$(kubectl get pods --namespace dagster -l "app.kubernetes.io/name=dagster,app.kubernetes.io/instance=dagster,component=dagster-webserver" -o jsonpath="{.items[0].metadata.name}")
> ...

kubectl get pods --namespace dagster -l "app.kubernetes.io/name=dagster,app.kubernetes.io/instance=dagster,component=dagster-webserver" -o jsonpath="{.items[0].metadata.name}"
> dagster-dagster-webserver-5d7cc9d99b-jh8ql
```