Pin onnx (#29944)
https://buildkite.com/dagster/dagster-dagster/builds/122390#0196ca05-6e98-422d-98e1-9146922c2ec2/451-507

```
E   ImportError: cannot import name 'split_complex_to_pairs' from 'onnx.helper'
```

Looks like 1.18.0 introduced a breaking change. Pinning around it for
now.