Ignore run attribution missing return
```
docs_snippets/guides/dagster/run_attribution/custom_run_coordinator_skeleton.py:11: error: Missing return statement  [return]
```

This is just a partial snippet; no need to return