Improve error message for @solid without positional context parameter
Summary:
Replaces:

```
dagster.core.errors.DagsterInvalidDefinitionError: solid 'expectations_solid' decorated function
does not have required positional parameter 'None'. Solid functions should only have keyword arguments
that match input names and a first positional parameter named 'context'.
```

with:

```
dagster.core.errors.DagsterInvalidDefinitionError: solid 'expectations_solid' decorated function
does not have required positional parameter 'context'. Solid functions should only have keyword arguments
that match input names and a first positional parameter named 'context'.
```

Test Plan: Unit

Reviewers: schrockn, alangenfeld

Reviewed By: alangenfeld

Differential Revision: https://dagster.phacility.com/D589