Modify case for upload_fileobj() to match boto3 (#16423)
## Summary & Motivation

This PR implements the modification proposed in issue #16422.

In `S3FakeResource`, all methods follow the same signature as boto3,
namely capitalized parameter names, except for `upload_fileobj()`.

- S3FakeResource.upload_fileobj() signature: `def upload_fileobj(self,
fileobj, bucket, key, *args, **kwargs)`
- boto3 S3.Client.upload_fileobj() signature:
`S3.Client.upload_fileobj(Fileobj, Bucket, Key, ExtraArgs=None,
Callback=None, Config=None)`

The mismatching case can cause the following error when unit testing
code using s3 resource with keyword arguments:
`TypeError: upload_fileobj() missing 3 required positional arguments:
'fileobj', 'bucket', and 'key'`

With this PR, I suggest to rename parameters in
`S3FakeResource.upload_fileobj()` to match the case found in boto3:
`def upload_fileobj(self, Fileobj, Bucket, Key, *args, **kwargs)`

## How I Tested These Changes