Raise a bespoke `ImportError` when importing `FreshnessPolicy` from top-level Dagster (#30855)
## Summary & Motivation
User code should fail to compile with an `ImportError` when it tries to import `FreshnessPolicy` from top-level Dagster module.

```
from dagster import FreshnessPolicy
```
raises:
```
ImportError: FreshnessPolicy has been renamed to LegacyFreshnessPolicy. Import it as FreshnessPolicy from `dagster.deprecated` or as LegacyFreshnessPolicy from top-level Dagster.
```
Without this PR, user code will still fail with an `ImportError` - it just won't have the nice error message.

We'll remove this `ImportError` once the new freshness policy model (currently named `InternalFreshnessPolicy`) is moved out of preview and assumes the name `FreshnessPolicy`.

## How I Tested These Changes
a unit test added in this PR

## Changelog

> Insert changelog entry or delete this section.
- Adds a custom error message when importing `FreshnessPolicy` from the `dagster` module

(cherry picked from commit a8a26785ff580f7c04bf2655b803adc61b26e2fe)