Remove skipped grpc tests
Our `wait_for_connection` function has been masking test failures
for a long time because it skips the test if the grpc container cannot
launch instead of failing it:

https://github.com/dagster-io/dagster/blob/7c38a8c022c4d7343980317574a74139d31da888/python_modules/dagster/dagster_tests/conftest.py#L72-L75

Our grpc container has been failing for a while now and we haven't
noticed. It uses some very old, deprecated Dagster APIs and has been
failing to launch because:

```
  File "test_pipelines/repo.py", line 122, in bar_repo
    "schedules": define_bar_schedules(),
  File "test_pipelines/repo.py", line 60, in define_bar_schedules
    "foo_schedule": ScheduleDefinition(
TypeError: __init__() got an unexpected keyword argument 'pipeline_name'
```

The tests in question are:

dagster_tests/api_tests/test_api_list_repositories.py::test_sync_list_container_grpc
dagster_tests/general_tests/grpc_tests/test_persistent_container.py::test_ping
dagster_tests/general_tests/grpc_tests/test_persistent_container.py::test_streaming

I didn't fully bisect the change, but these are skipped at least as
early as Dagster 0.12.0 which was released back in July 2021.

https://buildkite.com/dagster/dagster/builds/18299

One option is to fix the repo. The fix itself would be trival (replace
the rather complicated legacy repo with simpler modern one).

Another is to remove the tests (and the accompanying fixtures - and by
extension, the handful of other tests that rely on those fixtures)
because they haven't been providing any coverage for well over a year
now and this type of behavior is well flexed throughout our various
integration tests.

I stopped short of removing the test project entirely because I couldn't
really tell if other things are relying on it.