Use Config class instead of base class kwargs in structured config to not break early pydantic versions (#11546)
### Summary & Motivation

We were using base class kwargs arguments in Pydantic in the structured config workstream. This breaks pydantic <1.8. Using `Config` class instead of kwargs.

### How I Tested These Changes

```
dagster-x86-3.10.3) elementl-13in-m1-mbppro-2021:script_to_assets_branching_io_manager schrockn$ pip list | grep pydantic
pydantic                            1.7.4
(dagster-x86-3.10.3) elementl-13in-m1-mbppro-2021:script_to_assets_branching_io_manager schrockn$ pytest /Users/schrockn/code/dagster/python_modules/dagster/dagster_tests/core_tests/structured_config_tests/test_basic_structured_config.py

This error occurred:
....
TypeError: MakeConfigCacheable.__init_subclass__() takes no keyword arguments

(dagster-x86-3.10.3) elementl-13in-m1-mbppro-2021:script_to_assets_branching_io_manager schrockn$ git co fix-pydantic
Switched to branch 'fix-pydantic'
(dagster-x86-3.10.3) elementl-13in-m1-mbppro-2021:script_to_assets_branching_io_manager schrockn$ !pyt
pytest /Users/schrockn/code/dagster/python_modules/dagster/dagster_tests/core_tests/structured_config_tests/test_basic_structured_config.py
WARNING:root:Unable to detect CI environment.  No test analytics will be sent.
================================================================================= test session starts ==================================================================================
platform darwin -- Python 3.10.3, pytest-7.0.1, pluggy-1.0.0
rootdir: /Users/schrockn/code/dagster, configfile: pyproject.toml
plugins: forked-1.4.0, structlog-0.5, ddtrace-1.6.1, buildkite-test-collector-0.1.3, dependency-0.5.1, requests-mock-1.10.0, snapshottest-0.6.0, xdist-2.1.0, mock-3.3.1, cov-2.10.1, respx-0.20.0, anyio-3.6.2, rerunfailures-10.0
collected 22 items

../../../python_modules/dagster/dagster_tests/core_tests/structured_config_tests/test_basic_structured_config.py ......................                                          [100%]

================================================================================== 22 passed in 0.59s ==================================================================================
```