MetadataValue subclasses to DagsterModel (#21324)
## Summary & Motivation

This is a tricky one because it lies at the intersection of generics,
inheritance, and pydantic. I tried a bunch of different approaches here.
The obvious approach, where `IntMetadataValue` has a `value:
Optional[int]`, raises this error:
```
NameError: Field name "value" shadows an attribute in parent "MetadataValue"; you might want to use a different field name with "alias='value'".
```

This approach depends on serializing using field aliases:
https://github.com/dagster-io/dagster/pull/21325.

## How I Tested These Changes