[dg] Get cli plumbing working for new --format argument (#28845)
## Summary & Motivation

Just getting the double layer cli layering working before implementing the business logic.

* `dg` has a flag (`--format`) that defaults to `yaml`)
* `dagster_componets` has a non-optional flag (`--scaffold-format`). Renamed to avoid collision with python built-in `format`.

## How I Tested These Changes

```
(dagster-dev-3.11.11-2024-12-08) ➜  standalone_project dg scaffold dagster_components.dagster.DefinitionsComponent test_component_1 --format python
Using /Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/bin/dagster-components
Traceback (most recent call last):
  File "/Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/bin/dagster-components", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-components/dagster_components/cli/__init__.py", line 35, in main
    cli(auto_envvar_prefix=ENV_PREFIX)
  File "/Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py", line 47, in scaffold_object_command
    scaffold_object(path, obj, typename, scaffold_params, scaffold_format)
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-components/dagster_components/component_scaffolding.py", line 65, in scaffold_object
    scaffolder.scaffold(
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/scaffolder.py", line 33, in scaffold
    scaffold_component(
  File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-components/dagster_components/component_scaffolding.py", line 37, in scaffold_component
    raise NotImplementedError("Python scaffolding not yet implemented.")
NotImplementedError: Python scaffolding not yet implemented.
An error occurred while executing a `dagster-components` command in the Python environment at /Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv.

`uv run dagster-components scaffold object dagster_components.dagster.DefinitionsComponent /Users/schrockn/code/scratch/dg-workspaces/standalone_project/standalone_project/defs/test_component_1 --scaffold-format python` exited with code 1. Aborting.
(dagster-dev-3.11.11-2024-12-08) ➜  standalone_project
```
## Changelog

> Insert changelog entry or delete this section.