Update tutorial.py
This will fix an error below

```
2025-09-05 10:22:58 +0900 - dagster - ERROR - Validation failed for code location dagster-tutorial:

dagster._core.errors.DagsterInvalidDefinitionError: resource with key 'database' required by op 'customers' was not provided. Please provide a ResourceDefinition to key 'database', or change the required key to one of the following keys which points to an ResourceDefinition: ['io_manager', 'duckdb']

Stack Trace:
  [17 dagster system frames hidden, run with --verbose to see the full stack trace]

2025-09-05 10:22:58 +0900 - dagster - ERROR - Validation for 1 code locations failed.
```