Dagster k8s better handling of failed jobs (#16303)
## Summary & Motivation

Hello,

This is a relatively minor change to library `dagster-k8s` such that it
deals better with cases in which the Kubernetes job has both failed and
active jobs. In this way situations such as those described in #6236 are
better handled.

This is the first time contributing to this project. I have followed the
[contributing guide](https://docs.dagster.io/community/contributing) and
hopefully everything is fine.

I look forward to your comments!

## How I Tested These Changes

I prepared the new unit test by running an existing job on Kubernetes
with `backoff_limit: 3` and deleting the pod manually to trigger
re-execution. Without this change exception `DagsterK8sError` is raised
as:

```
dagster_k8s.client.DagsterK8sError: Encountered failed job pods for job dagster-step-4042dc71c0e6a277db11063e58ed74b1-1 with status: {'active': 1,
 'completed_indexes': None,
 'completion_time': None,
 'conditions': None,
 'failed': 1,
 'ready': 0,
 'start_time': datetime.datetime(2023, 9, 3, 16, 50, 10, tzinfo=tzlocal()),
 'succeeded': None,
 'uncounted_terminated_pods': {'failed': None, 'succeeded': None}}, in namespace <namespace>

  File "/usr/local/lib/python3.10/site-packages/dagster_celery_k8s/executor.py", line 450, in _execute_step_k8s_job
    api_client.wait_for_job_success(
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/client.py", line 350, in wait_for_job_success
    self.wait_for_running_job_to_succeed(
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/client.py", line 399, in wait_for_running_job_to_succeed
    raise DagsterK8sError(
```

I monitored using `kubectl` what was running and Kubernetes correctly
started a new pod, which means that dictionary `status` contains
`active: 1`. Therefore, I added the new statement to the conditional as
you can see in the diff. In the unit test two jobs are returned with
these properties to test that the job is correctly recognized as
successful.

The changes to `retrieve_pod_logs` are needed because when pods are
deleted and restarted, for example because the node is drained, its logs
can no longer be retrieved (or the pod is in a state that does not
return any logs) and instead an exception is raised:

```
kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '5c51576a-42e6-4072-8f16-2e53f86534c3', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Sun, 03 Sep 2023 16:51:10 GMT', 'Content-Length': '240'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \\"dagster\\" in pod \\"dagster-step-4042dc71c0e6a277db11063e58ed74b1-1-8kh59\\" is waiting to start: ContainerCreating","reason":"BadRequest","code":400}\n'


  File "/usr/local/lib/python3.10/site-packages/dagster_celery_k8s/executor.py", line 532, in _execute_step_k8s_job
    raw_logs = api_client.retrieve_pod_logs(pod_name, namespace=job_namespace)
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/client.py", line 667, in retrieve_pod_logs
    return self.core_api.read_namespaced_pod_log(
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 23957, in read_namespaced_pod_log
    return self.read_namespaced_pod_log_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 24076, in read_namespaced_pod_log_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 241, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 235, in request
    raise ApiException(http_resp=r)
```

With this change the log is not retrieved (an empty string is instead
returned, suggestions welcome to better handle this scenario) but the
exception is not raised further.

---------

Co-authored-by: fgarciaf <francisco.garciaflorez@asml.com>