pin uv (#24398)
pretty sure its https://github.com/astral-sh/uv/issues/7284 we are
hitting

add and share uv pin to `0.4.8` 

error we are observing for reference
```

error: Failed to prepare distributions
--
  | [2024-09-11T00:41:02Z]   Caused by: Failed to fetch wheel: minimal-snowplow-tracker==0.0.2
  | [2024-09-11T00:41:02Z]   Caused by: /root/.cache/uv/built-wheels-v3/pypi/minimal-snowplow-tracker/0.0.2/F7CAlaBs9KulatdPNgAiL/b57c20fa08c7fa71/minimal-snowplow-tracker-0.0.2.tar.gz does not appear to be a Python project, as neither `pyproject.toml` nor `setup.py` are present in the directory
  | [2024-09-11T00:41:02Z] Partially built virtualenv for pyright environment alt-1 deleted.
  | [2024-09-11T00:41:02Z] Traceback (most recent call last):
  | [2024-09-11T00:41:02Z]   File "/workdir/scripts/run-pyright.py", line 577, in <module>
  | [2024-09-11T00:41:02Z]     normalize_env(
  | [2024-09-11T00:41:02Z]   File "/workdir/scripts/run-pyright.py", line 346, in normalize_env
  | [2024-09-11T00:41:02Z]     raise e
  | [2024-09-11T00:41:02Z]   File "/workdir/scripts/run-pyright.py", line 341, in normalize_env
  | [2024-09-11T00:41:02Z]     subprocess.run(build_venv_cmd, shell=True, check=True)
  | [2024-09-11T00:41:02Z]   File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
  | [2024-09-11T00:41:02Z]     raise CalledProcessError(retcode, process.args,
  | [2024-09-11T00:41:02Z] subprocess.CalledProcessError: Command 'uv venv --python=/usr/local/bin/python --seed /workdir/pyright/alt-1/.venv && uv pip install --python /workdir/pyright/alt-1/.venv/bin/python -U pip setuptools wheel && uv pip install --python /workdir/pyright/alt-1/.venv/bin/python --config-settings editable-mode=compat -r requirements-alt-1.txt  --no-deps --reinstall-package assets_pandas_type_metadata --reinstall-package dagster --reinstall-package dagster_webserver --reinstall-package dagster_graphql --reinstall-package dagster_pandera --reinstall-package project_fully_featured --reinstall-package dagster --reinstall-package dagster_pipes --reinstall-package dagster_webserver --reinstall-package dagster_graphql --reinstall-package dagster_aws --reinstall-package dagster_dbt --reinstall-package dagster_duckdb_pandas --reinstall-package dagster_duckdb --reinstall-package dagster_duckdb_pyspark --reinstall-package dagster_pandas --reinstall-package dagster_postgres --reinstall-package dagster_polars --reinstall-package dagster_gcp --reinstall-package dagster_pyspark --reinstall-package dagster_slack --reinstall-package dagster_spark --reinstall-package dagster_snowflake --reinstall-package dagster_snowflake_pandas --reinstall-package dagster_snowflake_pyspark' returned non-zero exit status 2.
  | [2024-09-11T00:41:02Z] make: *** [Makefile:10: pyright] Error 1


```