autoMaterializeAssetEvaluations make cursor not required (#14461)
The gql type is optional but no default was provided to the resolver, so it could raise `TypeError: resolve_autoMaterializeAssetEvaluations() missing 1 required positional argument: 'cursor'\n"`