[dagster-tableau] Raise exception on invalid or empty workbook data (#25653)
## Summary & Motivation

This exception was encountered when dogfooding the `dagster-tableau`
integration:

```bash
  File "/Users/owen/src/dagster/scratch/tableau.py", line 27, in <module>
    tableau_specs = load_tableau_asset_specs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/decorator_utils.py", line 203, in wrapped_with_pre_call_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/libraries/dagster-tableau/dagster_tableau/resources.py", line 485, in load_tableau_asset_specs
    .build_defs()
     ^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/definitions_load_context.py", line 181, in build_defs
    else self.fetch_state()
         ^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/libraries/dagster-tableau/dagster_tableau/resources.py", line 539, in fetch_state
    workspace_data: TableauWorkspaceData = self.workspace.fetch_tableau_workspace_data()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/libraries/dagster-tableau/dagster_tableau/resources.py", line 358, in fetch_tableau_workspace_data
    workbook_data = client.get_workbook(workbook_id=workbook_id)["data"]["workbooks"][0]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

It looks like a `workbook_id` obtained using `get_workbooks()` - Tableau
Rest API - did not exist yet when calling `get_workbook(workbook_id)` -
Tableau GraphQL API. The result:
`client.get_workbook(workbook_id=workbook_id)["data"]["workbooks"]` was
an empty list.

This may have happened because the workbook had just been created, but
it would be better to raise exceptions with custom messages if it
happens again.

This PR adds conditions and exceptions to make sure that the workbook
data list is a non empty list before accessing its first item.

## How I Tested These Changes

Additional unit tests