Surface how to visualize import performance issues (#26850)
## Summary & Motivation

Make finding the instructions for debugging import performance issues
more obvious.

## How I Tested These Changes

I ran code where I end up with an indirect `grpc` import, and the output
now looks like:

```python
        expensive_imports = [f"`{lib}`" for lib in expensive_library if lib in import_profile]
    
        # if `tuna` output is unfriendly, another way to debug imports is to open `/tmp/import.txt`
        # using https://kmichel.github.io/python-importtime-graph/
>       assert not expensive_imports, (
            "The following expensive libraries were imported with the top-level `dagster` module, "
            f"slowing down any process that imports Dagster: {', '.join(expensive_imports)}; to debug, "
            "`pip install tuna`, then run "
            "`python -X importtime python_modules/dagster/dagster_tests/general_tests/simple.py &> /tmp/import.txt && tuna /tmp/import.txt`."
        )
E       AssertionError: The following expensive libraries were imported with the top-level `dagster` module, slowing down any process that imports Dagster: `grpc`; to debug, `pip install tuna`, then run `python -X importtime python_modules/dagster/dagster_tests/general_tests/simple.py &> /tmp/import.txt && tuna /tmp/import.txt`.
E       assert not ['`grpc`']

python_modules/dagster/dagster_tests/general_tests/test_import.py:35: AssertionError
```

Note that the https://kmichel.github.io/python-importtime-graph/ isn't
directly raised, but it's placed in the code such that it gets displayed
to somebody reading the output anyway.

## Possible Alternatives

Just moving the existing comment above the asserts could work, since
that way the instructions would happen to appear in the output. I didn't
think about that earlier.