[docs] dagster essentials - fixes relative partitions import for taxi trips (#18132)
## Summary & Motivation

Imports of `monthly_partition` should use `..partitions` to import the
`monthly_partitions` object.

Without this, the following error is thrown:

```
The above exception was caused by the following exception:
ModuleNotFoundError: No module named 'dagster_university.assets.partitions'
```

Cheers!

## How I Tested These Changes

Viewed rendered markdown in web browser.