Fix serdes on FreshnessPolicy object (#12143)
## Summary

Fixes pickling/unpickling of `FreshnessPolicies` due to the `__new__`
signature, which was previously leading to this error:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ben/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/spawn.py", line 128, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/ben/.pyenv/versions/3.8.12/lib/python3.8/multiprocessing/spawn.py", line 141, in _main
    self = reduction.pickle.load(from_parent)
TypeError: __new__() takes 1 positional argument but 3 were given
```

This appears to be the root cause of e.g. #11822