Fixup k8s helm install command (#27587)
I was running through this recently and bumped up against:

```
Error: unknown flag: --install
```

I'm not sure if this is just a typo or reflects a change in the helm CLI
but I'm guessing the former.