Update changelog to reflect yank (#23873)
## Summary & Motivation

```
TypeError: PartitionArgs.__new__() missing 1 required positional argument: 'job_name'
```

We've yanked this version of Dagster from PyPI. Affected users should
downgrade to 1.8.2/0.24.2.

## Changelog [New | Bug | Docs]

> NOCHANGELOG