fix(dbt): divest from the quoted `relation_name` when building column lineage (#22821)
## Summary & Motivation

- Consolidate the column lineage metadata logic together in a single
conditional with a try/except similar to
https://github.com/dagster-io/dagster/pull/22641.
- Divest from using the quoted `relation_name`, and just use the
`database`, `schema`, `name`.
- Apply https://github.com/dagster-io/dagster/pull/22642 when building
the column lineage.

## How I Tested These Changes
This should probably be under nightly test against a real bigquery
instance.

Locally, things work now.

### Before

Materializing with `.fetch_column_metadata()` resulted in:

```
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "jaffle_shop_dbt_assets":
The above exception was caused by the following exception:
google.api_core.exceptions.BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/%60dagster-cloud-local-test%60/datasets/%60toys%60/tables/%60raw_customers%60?prettyPrint=false: Invalid resource name projects/`dagster-cloud-local-test`; Project id: `dagster-cloud-local-test`
```


### After

Bigquery assets materialize successfully with metadata:

![image](https://github.com/dagster-io/dagster/assets/16431325/63867fcf-d404-44ca-a06c-60989c79b744)