name mysql test fixtures (#17483)
Currently we see 

```
FAILED dagster_mysql_tests/test_event_log.py::TestMySQLEventLogStorage::test_materialization_tag_on_wipe[conn_string0]
```

I might have diagnosed the issue sooner if I saw [latest-db-version]
instead of [conn_string0]