[daggy-u][dbt] remove strptime for incremental model (#21425)
## Summary & Motivation

- the `%c` format string being used with `strptime` in this context does
not appropriately parse `pendulum.datetime` ISO timestampsa

linked: https://github.com/dagster-io/project-dagster-university/pull/23

## How I Tested These Changes

- Ran backfill of partitioned model

```python
>>> pendulum.now().isoformat()
'2024-04-25T11:45:47.749103-04:00'
```
```sql
D select strptime('2024-04-25T11:29:18.217685', '%c');
Invalid Input Error: Could not parse string "2024-04-25T11:29:18.217685" according to format specifier "%c"
2024-04-25T11:29:18.217685
          ^
Error: Space does not match, expected
```