[dg] Collapse load errors when invoking dg list defs (#29507)
## Summary

Collapse error messages when loading a repo for the purposes of `dg list
defs`, in a similar vein to what we do for `dg dev` and `dg check defs`:

```sh
$ dg list defs
Using /Users/ben/repos/components_demo/missing-resource-demo/.venv/bin/dagster-components
Loading location missing-resource-demo failed:

dagster._core.errors.DagsterInvalidDefinitionError: resource with key 'my_resource' required by op 'my_asset' was not provided. Please provide a ResourceDefinition to key 'my_resource', or change the required key to one of the following keys which points to an ResourceDefinition: ['io_manager']

Stack Trace:
  [15 dagster system frames hidden, run dg check defs --verbose to see the full stack trace]

An error occurred while executing a `dagster-components` command in the Python environment at /Users/ben/repos/components_demo/missing-resource-demo/.venv.

`uv run dagster-components list definitions --location missing-resource-demo --module-name missing_resource_demo.definitions --output-file /var/folders/bc/4npnrqyd46l4vbbkdsdsw3_h0000gn/T/tmpspyxetpf` exited with code 1. Aborting.
```

Users are instructed to call `dg check defs --verbose` to get the full
stacktrace.

## How I Tested These Changes

New unit test, tested locally.

## Changelog

> [dg] `dg list defs` now collapses long system stacktraces