[fix] Fix builtin type error related to resource annotations (#11551)
### Summary & Motivation

Addresses #11541, a bug introduced in #11322.

Users who are using Python >= 3.9 may use [builtin
types](https://peps.python.org/pep-0585/) for generic type annotations,
e.g. `list[dict[str, str]]` rather than `typing.List[typing.Dict[str,
str]]`.

Unfortunately, these builtin generics manage to get around the safety
checks in our subclass code - `isinstance(list[dict[str, str]], type) ==
True` and `inspect.isclass(list[dict[str, str]]) == True` but
`issubclass(list[dict[str, str]], Resource)` raises an error that
`list[dict[str, str]]` is not a class:

```python
TypeError: issubclass() arg 1 must be a class
```

This seems to be a specific issue related to `abc._abc_subclasscheck`,
since `Resource` is an ABC. The CPython implementation of the subclass
check seems to have different results than the python one, which uses
`isinstance(..., type)` under the hood:
https://bugs.python.org/issue44847

This PR adds a try/catch guard to areas where we make a subclass call to
avoid this issue.

## Test Plan

Add a test suite which is run for Python >= 3.9 to ensure builtin
generics can be used.