Fix test assertions
Summary:
str(exc_info) introduces ellipses in some configurations, so that tests fail with:

```
E       assert "@composite_solid 'config_fn_only' defines a configuration function <lambda> but does not define a configuration schema." in '<ExceptionInfo DagsterInvalidDefinitionError("@composite_solid \'config_fn_only\' defines a configuration function <l...chema. If you intend this composite to take no config_schema, you must explicitly specify config_schema={}.") tblen=3>'
E        +  where '<ExceptionInfo DagsterInvalidDefinitionError("@composite_solid \'config_fn_only\' defines a configuration function <l...chema. If you intend this composite to take no config_schema, you must explicitly specify config_schema={}.") tblen=3>' = str(<ExceptionInfo DagsterInvalidDefinitionError("@composite_solid 'config_fn_only' defines a configuration function <lamb...schema. If you intend this composite to take no config_schema, you must explicitly specify config_schema={}.") tblen=3>)
```

Test Plan: Unit local

Reviewers: alangenfeld, prha

Reviewed By: alangenfeld

Differential Revision: https://dagster.phacility.com/D3495