Revert "[RFC] feat(metadata): add table spec metadata" (#20613)
Reverts dagster-io/dagster#20597

I think this introduced a circular import that must not be fully under
test?

```
from dagster_graphql.implementation.events import iterate_metadata_entries
```

```
ImportError: cannot import name 'iterate_metadata_entries' from partially initialized module 'dagster_graphql.implementation.events' (most likely due to a circular import) (/dagster/python_modules/dagster-graphql/dagster_graphql/implementation/events.py)

```