[dagster definitions validate] Minimize validate logging (#27569)
## Summary

Reduce the default amount of logging for `dagster definitions validate`
by

- Clearing the root logger's handlers, if any are set (right now,
importing `dbt` in user code sets a handler)
- Captures warnings, meaning any error message from a code location
failing to load isn't directly printed but instead piped through to the
`validate` code.

```bash
$ dagster definitions validate

2025-02-04 14:41:18 -0800 - dagster - INFO - Validation successful for code location dagster_test.toys.repo.
2025-02-04 14:41:18 -0800 - dagster - INFO - All code locations passed validation.
```

```bash
$ dagster definitions validate

2025-02-04 14:41:04 -0800 - dagster - ERROR - Validation failed for code location dagster_test.toys.repo:

dagster._core.errors.DagsterInvalidDefinitionError: Input asset '["basic_asset_5"]' for asset '["basic_asset_4"]' is not produced by any of the provided asset ops and is not one of the provided sources. Did you mean one of the following?
	["basic_asset_1"], ["basic_asset_2"], ["basic_asset_3"], ["basic_asset_4"]

Stack Trace:
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/workspace/context.py", line 820, in _load_location
    else origin.create_location(self.instance)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/remote_representation/origin.py", line 203, in create_location
    return InProcessCodeLocation(self, instance=instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/remote_representation/code_location.py", line 386, in __init__
    self._loaded_repositories = LoadedRepositories(
                                ^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_grpc/server.py", line 250, in __init__
    loadable_targets = get_loadable_targets(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_grpc/utils.py", line 51, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/workspace/autodiscovery.py", line 32, in loadable_targets_from_python_module
    module = load_python_module(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/code_pointer.py", line 124, in load_python_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/.pyenv/versions/3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ben/repos/dagster/python_modules/dagster-test/dagster_test/toys/repo.py", line 139, in <module>
    @repository
     ^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py", line 402, in repository
    return _Repository()(definitions_fn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py", line 146, in __call__
    repository_data = CachingRepositoryData.from_list(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data.py", line 380, in from_list
    return build_caching_repository_data_from_list(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py", line 309, in build_caching_repository_data_from_list
    asset_graph = AssetGraph.from_assets(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/definitions/asset_graph.py", line 260, in from_assets
    assets_defs = cls.normalize_assets(assets)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/definitions/asset_graph.py", line 216, in normalize_assets
    resolved_deps = ResolvedAssetDependencies(assets_defs, [])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/definitions/resolved_asset_deps.py", line 24, in __init__
    self._deps_by_assets_def_id = resolve_assets_def_deps(assets_defs, source_assets)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/definitions/resolved_asset_deps.py", line 207, in resolve_assets_def_deps
    raise DagsterInvalidDefinitionError(msg)

2025-02-04 14:41:04 -0800 - dagster - ERROR - Validation for 1 code locations failed.
```

## Future Work

We could by default hide framework stacktraces, in cases like the above
where they're not very useful.


## Test Plan

Tested locally.

## Changelog

- `dagster definitions validate` is now less verbose, primarily
highlighting load errors