Fix regression when creating nested ConfigurableResource with pydantic >= v.2.5.0 (#28949)
## Summary

Slight tweak of @HynekBlaha's contribution in #28836 - this version
adjusts our Pydantic union behavior for resources to account for a
change in Pydantic 2.5.0 which uses 'smart unions'
(https://github.com/pydantic/pydantic-core/pull/867). This smart union
behavior attempted to initialize each member of the union using the
input data, which called the constructor for `PartialResource` with
invalid inputs.

This PR enforces left-to-right union evaluation, similar to what
occurred pre-Pydantic 2.5.0.

## Test Plan

Unit test introduced in #28836.

## Changelog

Fixed an issue where using partial resources in Pydantic >= 2.5.0 could
result in an unexpected keyword argument TypeError. (Thanks
[@HynekBlaha](https://github.com/HynekBlaha)!)

---------

Co-authored-by: Hynek Blaha <hynek.blaha@second-foundation.eu>