fix(dbt): support `MultiPartitionMapping` (#23363)
fix build_dbt_multi_asset_args to accept MultiParitionMapping:
- deps var was defined as a set, and was throwing an error when trying
to insert an AssetDep with a MultiPartitionMapping
- MultiPartitionMapping is taking in a dict, making it unhashable
Error I was getting
```
File "/Users/username/dev/data_orchestrations/project/internals/assets/dbt_assets.py", line 21, in dbt_asset_factory
    @dbt_assets(
     ^^^^^^^^^^^
  File "/Users/username/dev/data_orchestrations/project/.venv/lib/python3.12/site-packages/dagster/_core/decorator_utils.py", line 223, in wrapped_with_context_manager_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/username/dev/data_orchestrations/project/.venv/lib/python3.12/site-packages/dagster_dbt/asset_decorator.py", line 311, in dbt_assets
    ) = build_dbt_multi_asset_args(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/dev/data_orchestrations/project/.venv/lib/python3.12/site-packages/dagster_dbt/asset_utils.py", line 995, in build_dbt_multi_asset_args
    deps.add(
TypeError: unhashable type: 'dict'
```

## Summary & Motivation
I have flagged this issues while working on my own pipelines 

## How I Tested These Changes

Co-authored-by: Rex Ledesma <rex@dagsterlabs.com>