Ignore operator in ops snippets
```
docs_snippets/concepts/ops_jobs_graphs/ops.py:56: error: Unsupported operand types for % ("object" and "int")  [operator]
```

This snippet is just a proof of concept and not something we'd ever
expect somebody to copy/paste and use. It's fine if we're not first type
annotating our Callable.