Update AWS dependency and S3 clients (#1045)
Here’s a great example I hit today of where local dev sometimes falls down for data projects. 

So, the job was working fine locally, and worked on the “cluster” running on my laptop with local data, but when I switched to the cluster + S3 data, the job kept dying with
```
WARN  TaskSetManager:66 - Lost task 0.1 in stage 0.0 (TID 1, 192.168.51.154, executor 0): java.lang.NoClassDefFoundError: Could not initialize class io.dagster.events.EventPipeline$
....
Caused by: org.apache.spark.SparkException: A master URL must be set in your configuration
```

Turns out, it was because Spark was attempting to serialize the S3 client I was instantiating here: https://github.com/dagster-io/dagster/pull/1045/files#diff-370dff405f5d67934fbd312d5ab732d8L11

and ship it out to the executors. This, in turn, followed `final lazy val spark = SparkSession.builder.getOrCreate()` and ran this on the executor JVMs, which created empty Spark sessions on the executors.

What actually needs to happen is for the job to instantiate S3 clients on each executor JVM, and instantiating those clients can't depend on state in our master's `SparkSession`. 

To instantiate an S3 client on each executor, we use `mapPartitions`, which gives us an opportunity to instantiate one S3 client per `Dataset` partition instead of on the master or per record.

However, a more complicated problem is avoiding the need to access the S3 credentials previously stashed in the `SparkSession`. To do this, we needed to use the default S3 credential chain, which didn't yet exist in the legacy AWS library we were using. As documented in `build.sbt`, Spark depends on `hadoop-aws`, which transitively depends on `aws-java-sdk` 1.7.4. Importing a more recent version of `aws-java-sdk` breaks `hadoop-aws`, in turn preventing use of S3 in Spark reads/writes.

To circumvent this issue, this PR shades the `aws-java-sdk` jar. This avoids thrashing the transitive dependency at jar assembly time, ensuring that Spark can continue using the legacy 1.7.4 AWS dependency, while our client code uses 1.11.525.