Pin datahub (#14282)
Our datahub tests have been failing since 0.10.3 was pushed to PyPI on
Friday:

```
TypeError: DataHubRestEmitter.__init__() got an unexpected keyword argument 'server_telemetry_id'
```

I don't see a changelog and GitHub still shows 0.10.2 as the latest:

https://github.com/datahub-project/datahub

So I'm going to pin for now.