[dg check defs] Add hint about system frames being removed, --verbose flag (#28290)
## Summary

When system frames are stripped out of `dg check defs`/`dagster
definitions validate`, now notes that in the trace itself, and prompts
the user to pass the new `--verbose` flag if they would like to see an
unadulterated stacktrace.

```python
dlt.common.configuration.exceptions.ConfigFieldMissingException: Following fields are missing: ['thinkific_subdomain', 'thinkific_api_key'] in configuration with spec ThinkificConfiguration
	for field "thinkific_subdomain" config providers and keys were tried in following order:
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC__THINKIFIC_SUBDOMAIN was not found.
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC_SUBDOMAIN was not found.
		In Environment Variables key SOURCES__THINKIFIC_SUBDOMAIN was not found.
		In Environment Variables key THINKIFIC_SUBDOMAIN was not found.
	for field "thinkific_api_key" config providers and keys were tried in following order:
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC__THINKIFIC_API_KEY was not found.
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC_API_KEY was not found.
		In Environment Variables key SOURCES__THINKIFIC_API_KEY was not found.
		In Environment Variables key THINKIFIC_API_KEY was not found.
WARNING: dlt looks for .dlt folder in your current working directory and your cwd (/Users/ben/repos/internal/python_modules/dagster-open-platform) is different from directory of your pipeline script (/Users/ben/repos/dagster/python_modules/dagster/dagster).
If you keep your secret files in the same folder as your pipeline script but run your script from some other folder, secrets/configs will not be found
Please refer to https://dlthub.com/docs/general-usage/credentials/ for more information


Stack Trace:
  [11 system frames removed, run with --verbose to see the full stack trace]
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/dagster_open_platform/definitions.py", line 14, in <module>
    import dagster_open_platform.dlt.definitions as dlt_definitions
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/dagster_open_platform/dlt/definitions.py", line 21, in <module>
    from dagster_open_platform.dlt import assets
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/dagster_open_platform/dlt/assets.py", line 29, in <module>
    dlt_source=thinkific(),
               ^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/extract/decorators.py", line 199, in __call__
    source = self._deco_f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/extract/decorators.py", line 284, in _wrap
    rv = conf_f(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/inject.py", line 255, in _wrap
    config = resolve_config(bound_args, accept_partial_=accept_partial)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/inject.py", line 183, in resolve_config
    return resolve_configuration(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/resolve.py", line 67, in resolve_configuration
    return _resolve_configuration(config, sections, (), explicit_value, accept_partial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/resolve.py", line 164, in _resolve_configuration
    _resolve_config_fields(
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/resolve.py", line 304, in _resolve_config_fields
    raise ConfigFieldMissingException(type(config).__name__, unresolved_fields)
```

## How I Tested These Changes

New unit tests.