[docathon] remove invalid urls breaking docusaurus (#23942)
## Summary & Motivation

Resolves:
```
Error: MDX compilation failed for file "/Users/colton/src/dagster/docs/docs-beta/docs/apidocs/libraries/dagster-airbyte.md"
Cause: Can't parse URL https:/ with base unspecified://
Details:
Error: Can't parse URL https:/ with base unspecified://
```

## Changelog [New | Bug | Docs]

NOCHANGELOG