[dagster definitions validate] Unwrap, truncate user code errors (#28228)
## Summary

Tries to make `dg check defs` error messages more relevant by stripping
out the framework junk around a user code error.

Before:
```python
2025-03-04 15:06:30 -0800 - dagster - ERROR - Validation failed for code location dagster_open_platform:

dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
module_name=dagster_open_platform.definitions, working_directory=/Users/ben/repos/internal/python_modules/dagster-open-platform

Stack Trace:
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/workspace/context.py", line 819, in _load_location
    else origin.create_location(self.instance)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/remote_representation/origin.py", line 203, in create_location
    return InProcessCodeLocation(self, instance=instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/remote_representation/code_location.py", line 386, in __init__
    self._loaded_repositories = LoadedRepositories(
                                ^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_grpc/server.py", line 242, in __init__
    with user_code_error_boundary(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.9/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/errors.py", line 299, in user_code_error_boundary
    raise new_error from e

The above exception was caused by the following exception:
dlt.common.configuration.exceptions.ConfigFieldMissingException: Following fields are missing: ['thinkific_subdomain', 'thinkific_api_key'] in configuration with spec ThinkificConfiguration
	for field "thinkific_subdomain" config providers and keys were tried in following order:
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC__THINKIFIC_SUBDOMAIN was not found.
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC_SUBDOMAIN was not found.
		In Environment Variables key SOURCES__THINKIFIC_SUBDOMAIN was not found.
		In Environment Variables key THINKIFIC_SUBDOMAIN was not found.
	for field "thinkific_api_key" config providers and keys were tried in following order:
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC__THINKIFIC_API_KEY was not found.
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC_API_KEY was not found.
		In Environment Variables key SOURCES__THINKIFIC_API_KEY was not found.
		In Environment Variables key THINKIFIC_API_KEY was not found.
WARNING: dlt looks for .dlt folder in your current working directory and your cwd (/Users/ben/repos/internal/python_modules/dagster-open-platform) is different from directory of your pipeline script (/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/bin).
If you keep your secret files in the same folder as your pipeline script but run your script from some other folder, secrets/configs will not be found
Please refer to https://dlthub.com/docs/general-usage/credentials/ for more information


Stack Trace:
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/errors.py", line 289, in user_code_error_boundary
    yield
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_grpc/server.py", line 253, in __init__
    loadable_targets = get_loadable_targets(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_grpc/utils.py", line 51, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/workspace/autodiscovery.py", line 33, in loadable_targets_from_python_module
    module = load_python_module(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/code_pointer.py", line 135, in load_python_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.9/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/dagster_open_platform/definitions.py", line 14, in <module>
    import dagster_open_platform.dlt.definitions as dlt_definitions
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/dagster_open_platform/dlt/definitions.py", line 21, in <module>
    from dagster_open_platform.dlt import assets
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/dagster_open_platform/dlt/assets.py", line 29, in <module>
    dlt_source=thinkific(),
               ^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/extract/decorators.py", line 199, in __call__
    source = self._deco_f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/extract/decorators.py", line 284, in _wrap
    rv = conf_f(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/inject.py", line 255, in _wrap
    config = resolve_config(bound_args, accept_partial_=accept_partial)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/inject.py", line 183, in resolve_config
    return resolve_configuration(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/resolve.py", line 67, in resolve_configuration
    return _resolve_configuration(config, sections, (), explicit_value, accept_partial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/resolve.py", line 164, in _resolve_configuration
    _resolve_config_fields(
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/resolve.py", line 304, in _resolve_config_fields
    raise ConfigFieldMissingException(type(config).__name__, unresolved_fields)

2025-03-04 15:06:30 -0800 - dagster - ERROR - Validation for 1 code locations failed.
```

After:
```python
2025-03-04 15:06:50 -0800 - dagster - ERROR - Validation failed for code location dagster_open_platform:

dlt.common.configuration.exceptions.ConfigFieldMissingException: Following fields are missing: ['thinkific_subdomain', 'thinkific_api_key'] in configuration with spec ThinkificConfiguration
	for field "thinkific_subdomain" config providers and keys were tried in following order:
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC__THINKIFIC_SUBDOMAIN was not found.
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC_SUBDOMAIN was not found.
		In Environment Variables key SOURCES__THINKIFIC_SUBDOMAIN was not found.
		In Environment Variables key THINKIFIC_SUBDOMAIN was not found.
	for field "thinkific_api_key" config providers and keys were tried in following order:
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC__THINKIFIC_API_KEY was not found.
		In Environment Variables key SOURCES__THINKIFIC__THINKIFIC_API_KEY was not found.
		In Environment Variables key SOURCES__THINKIFIC_API_KEY was not found.
		In Environment Variables key THINKIFIC_API_KEY was not found.
WARNING: dlt looks for .dlt folder in your current working directory and your cwd (/Users/ben/repos/internal/python_modules/dagster-open-platform) is different from directory of your pipeline script (/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/bin).
If you keep your secret files in the same folder as your pipeline script but run your script from some other folder, secrets/configs will not be found
Please refer to https://dlthub.com/docs/general-usage/credentials/ for more information


Stack Trace:
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/dagster_open_platform/definitions.py", line 14, in <module>
    import dagster_open_platform.dlt.definitions as dlt_definitions
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/dagster_open_platform/dlt/definitions.py", line 21, in <module>
    from dagster_open_platform.dlt import assets
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/dagster_open_platform/dlt/assets.py", line 29, in <module>
    dlt_source=thinkific(),
               ^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/extract/decorators.py", line 199, in __call__
    source = self._deco_f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/extract/decorators.py", line 284, in _wrap
    rv = conf_f(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/inject.py", line 255, in _wrap
    config = resolve_config(bound_args, accept_partial_=accept_partial)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/inject.py", line 183, in resolve_config
    return resolve_configuration(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/resolve.py", line 67, in resolve_configuration
    return _resolve_configuration(config, sections, (), explicit_value, accept_partial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/resolve.py", line 164, in _resolve_configuration
    _resolve_config_fields(
  File "/Users/ben/repos/internal/python_modules/dagster-open-platform/.venv/lib/python3.12/site-packages/dlt/common/configuration/resolve.py", line 304, in _resolve_config_fields
    raise ConfigFieldMissingException(type(config).__name__, unresolved_fields)

2025-03-04 15:06:50 -0800 - dagster - ERROR - Validation for 1 code locations failed.

```

## Test Plan

Unit test.