Fix daemon liveness check command
Summary:
Looks like command couldn't run since the click option wasn't explicitly defined

```
  File "/usr/local/bin/dagster-daemon", line 33, in <module>
    sys.exit(load_entry_point('dagster', 'console_scripts', 'dagster-daemon')())
  File "/dagster/dagster/daemon/cli/__init__.py", line 141, in main
    cli(obj={})  # pylint:disable=E1123
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: liveness_check_command() got an unexpected keyword argument 'heartbeat_tolerance'

```

Test Plan: go/dev

Reviewers: dgibson

Reviewed By: dgibson

Differential Revision: https://dagster.phacility.com/D7707