Change dbt dependency to dbt-core in hacker-news example
Summary:
Attempt to resolve this error:
```
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cxzjirl0/dbt_5225a0719d94471e81a7ee131710fe6e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cxzjirl0/dbt_5225a0719d94471e81a7ee131710fe6e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o7ad7tj3
         cwd: /tmp/pip-install-cxzjirl0/dbt_5225a0719d94471e81a7ee131710fe6e/
    Complete output (21 lines):

    As of v1.0.0, `pip install dbt` is no longer supported.
    Instead, please use one of the following.

    **To use dbt with your specific database, platform, or query engine:**

        pip install dbt-<adapter>

        See full list: https://docs.getdbt.com/docs/available-adapters

    **For developers of integrations with dbt Core:**

        pip install dbt-core

        Be advised, dbt Cores python API is not yet stable or documented
        (https://docs.getdbt.com/docs/running-a-dbt-project/dbt-api)

    **For the previous behavior of `pip install dbt`:**

        pip install dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery
```