[docs] change HTTPS to HTTP in GraphQL API example (#17373)
## Summary & Motivation
If I start up the example project locally with `dagster dev` and then
try to connect to the GraphQL endpoint with`gql` using the link in the
example, I get an `SSL_WRONG_VERSION` error. I also get this error if I
use `dagster_graphql.DagsterGraphQLClient` with `use_https=True`.

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:992)')))
```

I figured out that the error means I'm trying to connect to something
that doesn't use HTTPS. Here's an example of someone explaining the
error:
https://github.com/psf/requests/issues/5943#issuecomment-925930558

## How I Tested These Changes

If I change the link to instead use HTTP, `gql` successfully connects
and queries the endpoint. `dagster_graphql.DagsterGraphQLClient` works
as expected if I set `use_https=False`.