[auto-materialize] Raise a more informative error message when getting a partition mapping failure (#17925)
## Summary & Motivation

When doing an AMP tick, it's generally necessary to calculate the set of
assets with updated parents. To do so, we need to get the set of updated
asset partitions, then map those to the children that those updates
impact.

If there's an error during partition mapping, it can be hard to know
exactly which two assets this failure happened between, which can be
very hard to debug in cases where there are hundreds or thousands of
assets.

This PR adds extra context to the error message, giving the names of the
assets for which the partition mapping failed.

As a bonus, adds a bit more information to a specific partition mapping
error.

## How I Tested These Changes

Verified that the following error message is surfaced in the UI upon
this type of failure:

```
dagster._core.errors.DagsterInvalidDefinitionError: Could not map partitions between parent ["foo"] and child ["bar"].
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_daemon/asset_daemon.py", line 379, in _run_iteration_impl
    ).evaluate()
      ^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py", line 550, in evaluate
    ) = self.get_auto_materialize_asset_evaluations()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py", line 465, in get_auto_materialize_asset_evaluations
    ) = self.evaluate_asset(asset_key, will_materialize_mapping, expected_data_time_mapping)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py", line 349, in evaluate_asset
    for evaluation_data, asset_partitions in materialize_rule.evaluate_for_asset(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py", line 655, in evaluate_for_asset
    ) in context.daemon_context.get_asset_partitions_with_newly_updated_parents_for_key(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py", line 291, in get_asset_partitions_with_newly_updated_parents_for_key
    ) = self._get_asset_partitions_with_newly_updated_parents_by_key_and_new_latest_storage_id()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_utils/cached_method.py", line 66, in _cached_method_wrapper
    result = method(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py", line 263, in _get_asset_partitions_with_newly_updated_parents_by_key_and_new_latest_storage_id
    ) = self.instance_queryer.asset_partitions_with_newly_updated_parents_and_new_latest_storage_id(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_utils/caching_instance_queryer.py", line 603, in asset_partitions_with_newly_updated_parents_and_new_latest_storage_id
    raise DagsterInvalidDefinitionError(
The above exception was caused by the following exception:
dagster._core.errors.DagsterInvalidDefinitionError: Timezones UTC and US/Central don't match
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_utils/caching_instance_queryer.py", line 594, in asset_partitions_with_newly_updated_parents_and_new_latest_storage_id
    partition_mapping.get_downstream_partitions_for_partitions(
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py", line 138, in get_downstream_partitions_for_partitions
    return self._map_partitions(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py", line 185, in _map_partitions
    raise DagsterInvalidDefinitionError(
```