[docs] add return for multi_asset api doc example (#15621)
The example as is doesn't work currently, you would get
```
dagster._core.errors.DagsterInvariantViolationError: op "my_function" has multiple outputs, but only one output was returned of type <class 'NoneType'>. When using multiple outputs, either yield each output, or return a tuple containing a value for each output. Check out the documentation on outputs for more: https://docs.dagster.io/concepts/ops-jobs-graphs/ops#outputs.
```

This change just updates the example to a working state.

An alternative path is make the current code work by treating a returned
`None` as "assume everything was materialized correctly" which is
explored in stacked PR https://github.com/dagster-io/dagster/pull/15622

## How I Tested These Changes

execute the example before and after