fix: use type name when displaying resource requirement exception (#16325)
## Summary & Motivation
Change the following:

```
dagster._core.errors.DagsterInvalidDefinitionError: resource with key 'dbt' required by op 'sca_custom_assets' was not provided. Please provide a <class 'dagster._core.definitions.resource_definition.ResourceDefinition'> to key 'dbt', or change the required key to one of the following keys which points to an <class 'dagster._core.definitions.resource_definition.ResourceDefinition'>: ['io_manager']
```

to:

```
dagster._core.errors.DagsterInvalidDefinitionError: resource with key 'dbt' required by op 'sca_custom_assets' was not provided. Please provide a ResourceDefinition to key 'dbt', or change the required key to one of the following keys which points to an ResourceDefinition: ['io_manager']
```

The "or change the required key..." should probably be changed as well.
Seeing the magic string `"io_manager"` here doesn't make sense, and
recommendations to use an IOManager key should only be made if the
current resource requirement is an io manager.

## How I Tested These Changes
local