[docs tests] Add debug makefile entrypoint for docs tests (#28263)
## Summary

When the docs integrations tests fail, the tempdirs are cleaned up and
evidence of the project state at the time the test failed is erased.
This PR adds a new makefile target `make
regenerate_cli_snippets_and_test_debug` which runs tests in
`/tmp/cli_snippets/{test_file_name}`, so that the results are preseved
afterwards to inspect in the case of success or failure.

```sh
$ make regenerate_cli_snippets_and_test

...
============================================= short test summary info ==============================================
FAILED docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py::test_components_docs_index - subprocess.CalledProcessError: Command 'dg check yzaml && echo "PWD=$(pwd);"' returned non-zero exit status 2.

Snippet regeneration failed. Please check the logs for more information. Working directory: /tmp/cli_snippets
make: *** [regenerate_cli_snippets_and_test] Error 1
```

```sh
$ tree /tmp/cli_snippets/test_components_docs

/tmp/cli_snippets/test_components_docs
└── jaffle-platform
    ├── dbt
    │   └── jdbt
    │       ├── README.md
    │       ├── dbt_project.yml
    │       ├── models
    │       │   ├── customers.sql
    │       │   ├── orders.sql
    │       │   ├── sources.yml
    │       │   └── stg
    │       │       ├── stg_customers.sql
    │       │       ├── stg_orders.sql
    │       │       └── stg_payments.sql
    │       └── profiles.yml
    ├── jaffle_platform
    │   ├── __init__.py
    │   ├── definitions.py
    │   ├── defs
    │   │   ├── ingest_files
    │   │   │   ├── component.yaml
    │   │   │   └── replication.yaml
    │   │   └── jdbt
    │   │       └── component.yaml
    │   └── lib
    │       ├── __init__.py
    ├── jaffle_platform_tests
    │   └── __init__.py
    ├── pyproject.toml
    ├── raw_customers.csv
    ├── raw_orders.csv
    ├── raw_payments.csv
    └── uv.lock

```

## How I Tested These Changes

Tested locally.