Fix resolution error with input manager key and custom dagster type (#12449)
Reported by a user:
https://dagster.slack.com/archives/C01U954MEER/p1676752453296759

Our input resolution logic misses an edge case that occurs when a custom
dagster type is used with an input manager key. This results in the
following error in graph resolution:
```
dagster._core.errors.DagsterInvalidDefinitionError: Input 'df_train' of op 'target_extractor_op' has no way of being resolved. Must provide a resolution to this input via another op/graph, or via a direct input value mapped from the top-level graph. To learn more, see the docs for unconnected inputs: https://docs.dagster.io/concepts/io-management/unconnected-inputs#unconnected-inputs.
```
This PR fixes this error.