Reimplement more helpful asset key mismatch errors round 2 (#20246)
## Summary

Reimplements #12460, which has been languishing for a long long time,
which was originally in #12008.


From the original PR:

> A little QoL idea that came out of our onboarding breakout group last
week. Adds a suggestion to the error message when an upstream asset dep
is not found, listing any assets with similar keys:
>
>  ```python
> dagster._core.errors.DagsterInvalidDefinitionError: Input asset
'["my", "asset1"]' for asset '["asset3"]'
> is not produced by any of the provided asset ops and is not one of the
provided sources.
>  Did you mean one of the following?
>      ["my", "prefix", "asset1"]
>  ```
>  



This implementation relies on the `rapidfuzz` library - #12460 was
shelved because it was unclear how much of an impediment the Visual C++
dep on Windows would be. This PR punts that until later and only uses
fuzzing if the library is already installed, rather than adding on a
dep.

This version of the PR adds the same hints to asset selection errors:


<img width="1297" alt="Screenshot 2024-03-04 at 3 05 35 PM"
src="https://github.com/dagster-io/dagster/assets/10215173/8ca9d959-86dd-4631-a297-06b8c87b176f">




Uses three heuristics for finding potential candiates:
- Same asset name, prefix is off-by-one component (e.g. `["snowflake',
"elementl", "prod", "my_asset"] vs ["snowflake", "elementl",
"my_asset"]`
- Asset selection uses slashes in place of actual keys (e.g.
`["snowflake/elementl/my_asset"] vs ["snowflake", "elementl",
"my_asset"]`)
- Same asset name, similar prefix (only if user has `rapidfuzz`
installed)
- Similar asset name, same prefix (only if user has `rapidfuzz`
installed)