pipe through dbt project in various places (#31742)
## Summary

We don't pipe through the dbt project in these helper methods, which
breaks `build_schedule_from_dbt_selection` for dbt component assets,
since we hit
```
dagster._core.errors.DagsterInvalidDefinitionError: Error resolving selection for asset job 
"rfm_segmentation_dbt_run": enable_code_references requires a DbtProject to be supplied to 
the @dbt_assets decorator.
```

## Test Plan

Update unit test with previously failing example.