Resolve ForwardRef issue on 3.12.(<4)
I ran into issues when my venv python version was 3.12.1 the other day.
Digging in, it looks like the `type_params` parameter to
`ForwardRef._evaluate` was only added in 3.12.4, but after #28960 we're
using it in 3.12.(<4)

(@alangenfeld ran into something similar in #22986, it looks like).

This moves the non-`type_params` branch to `< (3, 12, 4)`, and keeps
the `type_params` branch in the else.

== Test Plan

Make a venv for 3.12.1, build, and run:

```sh
uv venv --python 3.12.1
source .venv/bin/activate
make dev_install
dagster --version
```

Before, the following error would occur:

```
TypeError: ForwardRef._evaluate() got an unexpected keyword argument 'type_params'
```

After, you correctly see "dagster, version 1!0+dev"