Stub cpu and memory
Originally, these stubs didn't validate memory or cpu because our
initial ECS implementation didn't allow you to configure either. Now,
this more closely approximates how ECS actually behaves when registering
a task. Namely, it throws a client error when:

`memory` is not set. The real error looks like:

```
botocore.errorfactory.ClientException: An error occurred (ClientException)
when calling the RegisterTaskDefinition operation: Invalid setting for
container 'container'. At least one of 'memory' or 'memoryReservation'
must be specified.
```

`cpu` is not set. The real error looks like:

```
botocore.errorfactory.ClientException: An error occurred (ClientException)
when calling the RegisterTaskDefinition operation: Fargate requires that
'cpu' be defined at the task level.
```

There's an invalid `cpu` and `memory` combination. The real error looks
like:

```
botocore.errorfactory.ClientException: An error occurred (ClientException)
when calling the RegisterTaskDefinition operation: No Fargate
configuration exists for given values.
```

This stub is still incomplete and only implements the behavior necessary
to unit test the particular behavior we want to test. Particularly, it:
- Always validates memory and cpu against the Fargate constraints
  regardless of whether `requiresCompatibilities` is set. If we
  eventually support EC2, we'll want to extend this mock further.
- Only checks that `memory` and `cpu` are set at the top level of the
  keyword arguments; it doesn't check to see if they're set in the
  `containerDefinitions` or if `memoryReservation` is set. If we
  eventually support multiple containers in a task definition, we'll
  want to extend this mock further.