Wipe daemon heartbeats
Summary:
Since it is possible to introduce backcompat issues with heartbeats, this adds an escape hatch.

---

It seems that 'SensorDaemon` used to be written to storage, but we now depend on being able to recover the daemon_type value into an enum using `DaemonType(<retrieved val>)`.

```File "/opt/dagster/main_repo/python_modules/dagster/dagster/core/storage/runs/sql_run_storage.py", line 571, in get_daemon_heartbeats
    for row in rows
  File "/opt/dagster/main_repo/python_modules/dagster/dagster/core/storage/runs/sql_run_storage.py", line 571, in <dictcomp>
    for row in rows
  File "/usr/local/lib/python3.7/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.7/enum.py", line 569, in __new__
    raise exc
  File "/usr/local/lib/python3.7/enum.py", line 553, in __new__
    result = cls._missing_(value)
  File "/usr/local/lib/python3.7/enum.py", line 582, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'SensorDaemon' is not a valid DaemonType
```

Test Plan: Used locally

Reviewers: dgibson, max

Reviewed By: dgibson

Differential Revision: https://dagster.phacility.com/D5494