Addresses reason why dagster workspace cannot be reloaded
The existing course has forgotten to mention a small cleanup that is required in the job definition in order for the user to be able to successfully Reload the Dagster workspace. We add this in this commit.

Without this, Dagster will raise an error:

```
dagster._core.errors.DagsterInvalidDefinitionError: Selected assets must have the same partitions definitions, but the selected assets have different partitions definitions:
Monthly, starting 2023-01-01 UTC.: {AssetKey(['taxi_trips']), AssetKey(['taxi_trips_file'])}
Daily, starting 2023-01-01 UTC.: {AssetKey(['daily_metrics'])}
```

The Monthly partitioned job cannot contain an Asset that has daily partitions within it.