[docs] wip - generate code paths for webpack raw-loader efficiency (#27301)
## Summary & Motivation

**Edit** looks like the regex is missing one of the entries as indicated
by the failed Vercel build. Will look into this tomorrow.

```
Error: Can't render static file for pathname "/guides/build/partitions-and-backfills/defining-dependencies-between-partitioned-assets"
```

---

`raw-loader` was previously scanning the entire `examples/` folder, and
leaving many artifacts. Resulting in excessive memory usage (see memory
snapshot).


![image](https://github.com/user-attachments/assets/94265bed-5006-4c99-97d5-cf679a257d4b)

This introduces a build step to create a mapping of `CodeExample` paths
to their corresponding `import`, see improved memory snapshot.


![image](https://github.com/user-attachments/assets/a0c02622-e533-4980-91b6-e1574b9f2568)

@salazarm we discussed this offline at some point, but would definitely
appreciate your input on how this can be improved. Right off the bat,
I'm not sure if the regex works for components that span multiple lines.
Also want to get your input on if the _server_ conditional logic is
required. It seems to work with out it.

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.