fix: uv pip install requires `-e` on separate line (#23580)
## Summary & Motivation

```
$ make dev_install
python scripts/install_dev_python_modules.py
Requirement already satisfied: uv in ./.direnv/python-3.11/lib/python3.11/site-packages (0.2.35)

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
uv pip install -e python_modules/dagster[pyright,ruff,test] -e python_modules/dagster-pipes -e python_modules/dagster-graphql -e python_modules/dagster-test -e python_modules/dagster-webserver -e python_modules/dagit -e python_modules/automation -e python_modules/libraries/dagster-managed-elements -e python_modules/libraries/dagster-airbyte -e python_modules/libraries/dagster-aws[test] -e python_modules/libraries/dagster-celery -e python_modules/libraries/dagster-celery-docker -e python_modules/libraries/dagster-dask[yarn,pbs,kube] -e python_modules/libraries/dagster-databricks -e python_modules/libraries/dagster-datadog -e python_modules/libraries/dagster-datahub -e python_modules/libraries/dagster-dbt -e python_modules/libraries/dagster-docker -e python_modules/libraries/dagster-gcp -e python_modules/libraries/dagster-gcp-pandas -e python_modules/libraries/dagster-gcp-pyspark -e python_modules/libraries/dagster-embedded-elt -e python_modules/libraries/dagster-fivetran -e python_modules/libraries/dagster-k8s -e python_modules/libraries/dagster-celery-k8s -e python_modules/libraries/dagster-github -e python_modules/libraries/dagster-mlflow -e python_modules/libraries/dagster-mysql -e python_modules/libraries/dagster-looker -e python_modules/libraries/dagster-openai -e python_modules/libraries/dagster-pagerduty -e python_modules/libraries/dagster-pandas -e python_modules/libraries/dagster-papertrail -e python_modules/libraries/dagster-postgres -e python_modules/libraries/dagster-prometheus -e python_modules/libraries/dagster-pyspark -e python_modules/libraries/dagster-shell -e python_modules/libraries/dagster-slack -e python_modules/libraries/dagster-spark -e python_modules/libraries/dagster-ssh -e python_modules/libraries/dagster-twilio -e python_modules/libraries/dagstermill -e integration_tests/python_modules/dagster-k8s-test-infra -e python_modules/libraries/dagster-azure -e python_modules/libraries/dagster-msteams -e python_modules/libraries/dagster-deltalake -e python_modules/libraries/dagster-deltalake-pandas -e python_modules/libraries/dagster-deltalake-polars -e helm/dagster/schema[test] -e .buildkite/dagster-buildkite -e examples/experimental/dagster-blueprints -e examples/experimental/dagster-airlift -e python_modules/libraries/dagster-duckdb -e python_modules/libraries/dagster-duckdb-pandas -e python_modules/libraries/dagster-duckdb-polars -e python_modules/libraries/dagster-duckdb-pyspark -e python_modules/libraries/dagster-wandb -e python_modules/libraries/dagster-airflow -e python_modules/libraries/dagster-pandera -e python_modules/libraries/dagster-snowflake -e python_modules/libraries/dagster-snowflake-pandas -e python_modules/libraries/dagster-polars[deltalake,gcp,test]
error: Failed to parse: ` python_modules/dagster[pyright,ruff,test]`
  Caused by: Expected one of `@`, `(`, `<`, `=`, `>`, `~`, `!`, `;`, found `/`
 python_modules/dagster[pyright,ruff,test]
```

## How I Tested These Changes

```
make dev_install
```