Better error message for missing defs folder, allow list env without one (#31013)
## Summary

Addresses #30854. Adds a new `has_defs_path` property to the dg context
which can be used to alter command behavior if a defs folder is not
present. This is used for `dg list env`, which only uses the defs folder
to populate the list of components consuming env vars, a secondary piece
of functionality.

For cases where a defs folder is expected, `context.defs_path` will now
raise a clearer user-facing error about the missing `defs` folder.

```sh
$ dg list env
┏━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━┓
┃ Env Var ┃ Value ┃ Components ┃
┡━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━┩
│ FOO     │ ✓     │            │
└─────────┴───────┴────────────┘

$ dg check yaml
...
dagster_dg_core.error.DgError: Defs folder not found. Ensure folder `src/no_defs_demo/defs` exists in the project root.
```

## Test Plan

New unit tests for `dg list env` and for error messages with e.g. `dg
check yaml`.

## Changelog

[dg] dg list env now works properly in projects without a defs folder.